language: node_js

node_js:
  - '6'

# échoue dès qu'une erreur intervient
matrix:
  fast_finish: true

# met en cache node_modules, à noter que dans ce genre d’utilisation pour des
# bibliothèques open source consommées via npm, il ne faudra pas oublier
# npm prune utilisé ci-après, histoire de ne pas lancer des tests avec
# des paquets encore en cache mais non présents dans le package.json
cache:
  directories:
    - node_modules

before_install:
  - npm prune

#we use travis to generate the build
script: ./scripts/travis_script.sh

deploy:
  provider: heroku
  api_key:
    secure: RfK5EW11aVleYNlM57F/7g4Xypu+hRSxGuKncSFjylP6dbkxKNLKu3zFoVr1io38QS0C+m9xbQrxxoKd5dPg3W4DC45scehBXuZZv1WInJJDUoZE+bh8uqXQMJdExBAsuCKZbRZmKNy7J9MO9yRkSMBhULSdu3n7RqMtLBc/c2/3Ed4HaRHwOR3ioMhjC6WkyRapTHuq8X3avbjtwpZ5U0bBgEgqoYIraf0KPXU+EzXY3LX+hzQbLSUGS3w8cWDVJQbLOlnnZDfWPNa1FLtKPqcGpDc4Hu2Phabx7q6UJw9CpA0ZVjLJdHeBCmRxsw+Eeb5peDk2gMiBSaOtM3obr1o182aXcZta0iYTazkfV3EaSUYwJDzy/poGqAqhVRmp4fpJU3lmmBxJE0DnO+7SydgnDJ1p9P8cditdmSWluxwp+XHre7fbgYBZT9StGAHThTAXpx1DChl7RHXFCEyTIk0ZotY1C0EidZJ5Wz1ImdJ6csL/5z+EAsvH8rJ8gva1tJ6zb2NlHkgGf9+zrGmiCCjwH5ElwaXkphFpiC7Z0zPKP27MjUQm674Vf2GaldKlnE8MwXRG3jlxX/JCS/qvVDXxWFxMKiCvq9XiM+cBfmWwrxfvkwDyriqtWPbS8RaZN5nVmqcIgKvy82CpgLC13puk317dMEsoeaHI87dpG3E=
  app: explorest
  on:
    repo: Romathonat/ExploREST
