language: node_js

node_js:
  - '6'

# échoue dès qu'une erreur intervient
matrix:
  fast_finish: true

# met en cache node_modules, à noter que dans ce genre d’utilisation pour des
# bibliothèques open source consommées via npm, il ne faudra pas oublier
# npm prune utilisé ci-après, histoire de ne pas lancer des tests avec
# des paquets encore en cache mais non présents dans le package.json
cache:
  directories:
    - node_modules

before_install:
  - npm prune

#we use travis to generate the build, then to add the dist/ (the build) to heroku
script: ./scripts/travis_script.sh

#we deploy onto heroku
#the secure is the hash of the api key of the herokuapp (owner is Marc)
deploy:
  provider: heroku
  api_key:
    secure: "F6ZCC1YSc1Yhizx18X/RRVZ8cY0egMeZY79lnVCpJiVpESQwOwkQQKTQVK1/S75FtUMAhHvcOtHH+2x/FAkLswCRLuL9JBUipt1agcaoLFOAnON6eStzB/yBVN0btWNZxm++Qi0mUnWo5htGrXsGfOaCVb1vrnLGdEWMMxZPQ0YqhhEXiaQ0cMYiBpTX6KRYyjSId7K4gCFgJdiHZQOu1OXCEGLdD4MlKcbKWv6ehlNmKBuuNUwFKSKn0A0SWEGt3QOOvicXS2HSO50gCp3gNyUZp6ne+NVylPu2CKntWDYV1G0TLwcHPLc4dJwGV6qBeAOg1BqG1aheWasX707hSm5iFlETFhrn6OpZrP/mwKsL3X6CIndJ8MO+kTh6+BI4KRK8vUHDn15hVQQBSwwXzHPB3++WhQbZ6C8k1qa+2ARMTLs9ksof1oloaw60oZfVHxgXQ69AX9VDyS3SfFYWnd2UiYk7fLez5PwgQxESzbVKt5WeIiIJuTSXQVxU/YYqbc3GYUAXRXxpqskzm7bCJbGOBzYehvrAYx5B4w++zd5RgvBQWNeuWiOgOL7LSpMj+ru5CDH6ryBJbXQuov3VzNsfQfH61K17TtKNm6K9YdysDrAY2As+L/So+4AtMwA1Gwr6JgjyhlbF9SNCsFpzW5gXq6IwEZwRgA5u8DmvWkU="
  app: occinterface
